version: "3.8"
services:
  nextapp:
    container_name: nextapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:12
    container_name: db
    restart: always
    ports:
      - 5431:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data: {}
